<body>
	<div class="section">
		<div class="container">
			<main>
				<div class="columns">
					<div class="column is-full-mobile is-one-third-tablet">
						<div class="block">
							<div class="card">
								<header class="card-header">
									<p class="card-header-title">
										Vložit platbu
									</p>
								</header>
								<form action="" method="post">
									<div class="card-content">
										<div class="content">
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Jméno:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<div class="select is-fullwidth">
																<select autofocus name="admin-addpayment-userid">
																	<?php foreach ($this->data["familyUsers"] as $_user): ?>
																	<?php if ($_user["userid"] != Ssn::get("loggedUser")["userid"]): ?>
																	<option value="<?php echo $_user['userid']; ?>"
																		<?php if ((isset($_POST["admin-showpayments-userid"]) && $_POST["admin-showpayments-userid"] == $_user["userid"]) || (isset($_POST["admin-addpayment-userid"]) && $_POST["admin-addpayment-userid"] == $_user["userid"])): ?>
																			selected
																		<?php endif; ?>><?php echo $_user["username"]; ?></option>
																	<?php endif; ?>
																	<?php endforeach; ?>
																</select>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Měsíc:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<input class="input" type="number" min="1" max="12" name="admin-addpayment-month">
														</div>
													</div>
												</div>
											</div>
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Rok:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<input class="input" type="number" min="<?php echo '20'.date('y') ?>" max="2035" name="admin-addpayment-year">
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<footer class="card-footer">
										<input class="button is-fullwidth is-medium is-primary" type="submit" name="admin-addpayment" value="Přidat platbu">
									</footer>
								</form>
							</div>
						</div>
						<div class="block">
							<div class="card">
								<header class="card-header">
									<p class="card-header-title">
										Správa členů
									</p>
								</header>
								<form action="" method="post">
									<div class="card-content">
										<div class="content">
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Jméno:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<input class="input" type="text" name="admin-manageuser-username" required="required">
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<footer class="card-footer">
										<div class="card-footer-item">
											<input class="button is-left is-primary is-light is-medium is-fullwidth" type="submit" name="admin-adduser" value="Přidat člena">
										</div>
										<div class="card-footer-item">
											<input class="button is-right is-danger is-light is-medium is-fullwidth" type="submit" name="admin-deleteuser" value="Odebrat člena">
										</div>
									</footer>
								</form>
							</div>
						</div>
					</div>
					<div class="column is-full-mobile is-one-third-tablet">
						<div class="block">
							<div class="card">
								<header class="card-header">
									<p class="card-header-title">
										Seznam plateb
									</p>
								</header>
								<form action="" method="post">
									<div class="card-content">
										<div class="content">
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Jméno:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<div class="select is-fullwidth">
																<select autofocus name="admin-showpayments-userid">
																	<?php foreach ($this->data["familyUsers"] as $_user): ?>
																	<?php if ($_user["userid"] != Ssn::get("loggedUser")["userid"]): ?>
																	<option value="<?php echo $_user['userid']; ?>"
																		<?php if ((isset($_POST["admin-showpayments-userid"]) && $_POST["admin-showpayments-userid"] == $_user["userid"]) || (isset($_POST["admin-addpayment-userid"]) && $_POST["admin-addpayment-userid"] == $_user["userid"])): ?>
																			selected
																		<?php endif; ?>><?php echo $_user["username"]; ?></option>
																	<?php endif; ?>
																	<?php endforeach; ?>
																</select>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<footer class="card-footer">
										<input class="button is-light is-medium is-fullwidth" type="submit" name="admin-showpayments" value="Zobrazit platby">
									</footer>
								</form>
							</div>
						</div>
						<?php if (isset($this->data["show-payments"]) || isset($this->data["admin-addpayment"])): ?>
						<div class="block">
							<div class="card">
								<div class="card-content">
									<div class="content">
										<div class="table-container">
											<table class="table is-fullwidth is-hoverable has-text-centered">
											<thead>
												<tr>
													<th>Měsíc</th>
													<th>Rok</th>
													<th>Smazat</th>
												</tr>
											</thead>
											<tbody>
												<?php foreach ($this->data["show-payments"] as $_payment): ?>
												<tr
													<?php if ($_payment["month"] == (int)date("m")& $_payment["year"] == (int)"20".date("y")): ?>
													class="is-selected"
													<?php endif; ?>
													>
													<td><?php echo $_payment["month"] ?></td>
													<td><?php echo $_payment["year"] ?></td>
													<td>
														<form action="" method="post">
															<input type="hidden" name="admin-deletepayment-userid" value="<?php echo $_payment["userid"] ?>">
															<input type="hidden" name="admin-deletepayment-month" value="<?php echo $_payment["month"] ?>">
															<input type="hidden" name="admin-deletepayment-year" value="<?php echo $_payment["year"] ?>">
															<button type="submit" name="admin-deletepayment" class="button is-small is-danger is-light">
																<span class="icon is-small">
																	<i class="far fa-trash-alt"></i>
																</span>
															</button>
														</form>
													</td>
												</tr>
												<?php endforeach; ?>
											</tbody>
										</table>
										</div>
									</div>
								</div>
							</div>
						</div>
						<?php endif ?>
					</div>
					<div class="column is-full-mobile is-one-third-tablet">
						<div class="block">
							<div class="card">
								<header class="card-header">
									<p class="card-header-title">
										Uživatelské informace
									</p>
								</header>
								<div class="card-content">
									<div class="content">
										<p>Přihlášen jako <?php echo Ssn::get("loggedUser")["username"]?></br>(skupina <?php echo Ssn::get("loggedUser")["familyid"] ?>)</p>
									</div>
								</div>
								<form action="" method="post">
									<footer class="card-footer">
										<input class="button is-dark is-fullwidth is-medium" type="submit" name="logout" value="Odhlásit se">
									</footer>
								</form>
							</div>
						</div>
						<div class="block">
							<div class="card">
								<header class="card-header">
									<p class="card-header-title">
										Změna hesla
									</p>
								</header>
								<form action="" method="post">
									<div class="card-content">
										<div class="content">
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Heslo:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<input class="input" type="password" name="changepassword-password" required="required">
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card-footer">
										<input class="button is-light is-medium is-fullwidth" type="submit" name="changepassword" value="Změnit heslo">
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	</div>
</body>