<body>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-sm-8 mb-3">
                <div class="card">
                    <h5 class="card-header">Vložit platbu</h5>
                    <div class="card-body">
                        <form class="card-text" action="" method="post">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Jméno:</label>
                                <div class="col">
                                    <select autofocus name="admin-addpayment-user" class="form-control">
                                        <?php foreach ($this->data["familyUsers"] as $user): ?>
                                            <?php if ($user["userid"] != Ssn::get("loggedUser")["userid"]): ?>
                                                <option value="<?php echo $user['userid']; ?>"><?php echo $user["username"]; ?></option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Měsíc:</label>
                                <div class="col">
                                    <input class="form-control" type="number" min="1" max="12" name="admin-addpayment-month" required="required">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Rok:</label>
                                <div class="col">
                                    <input class="form-control" type="number" min="2019" max="2035" name="admin-addpayment-year" required="required">
                                </div>
                            </div>
                        </div>
                        <input class="btn btn-lg btn-success btn-block" type="submit" name="admin-addpayment" value="Přidat platbu">
                    </form>
                </div>
            </div>
            <div class="col-sm-4 mb-3">
                <div class="card">
                    <h5 class="card-header">Uživatelské informace</h5>
                    <div class="card-body">
                        <p>Přihlášen jako <?php echo Ssn::get("loggedUser")["username"]?></br>(skupina <?php echo Ssn::get("loggedUser")["familyid"] ?>)</p>
                    </div>
                    <form action="" method="post">
                        <input class="btn btn-danger btn-block" type="submit" name="logout" value="Odhlásit se">
                    </form>
                </div>
            </div>
            <div class="col-sm-4 mb-3">
                <div class="card">
                    <h5 class="card-header">Přidat člena</h5>
                    <form action="" method="post">
                        <div class="form-group row">
                            <div class="col mx-3 mt-3">
                                <input class="form-control" type="text" name="admin-adduser-username" required="required">
                            </div>
                        </div>
                        <input class="btn btn-success btn-block" type="submit" name="admin-adduser" value="Přidat člena">
                    </form>
                </div>
            </div>
            <div class="col-sm-4 mb-3">
                <div class="card">
                    <h5 class="card-header">Odebrat člena</h5>
                    <form action="" method="post">
                        <div class="form-group row">
                            <div class="col mx-3 mt-3">
                                <input class="form-control" type="text" name="admin-deleteuser-username" required="required">
                            </div>
                        </div>
                        <input class="btn btn-danger btn-block" type="submit" name="admin-deleteuser" value="Odebrat člena">
                    </form>
                </div>
            </div>
            <div class="col-sm-4 mb-3">
                <div class="card">
                    <h5 class="card-header">Změna hesla</h5>
                    <form action="" method="post">
                        <div class="form-group row">
                            <div class="col mx-3 mt-3">
                                <input class="form-control" type="password" name="changepassword-password" required="required">
                            </div>
                        </div>
                        <input class="btn btn-warning btn-block" type="submit" name="changepassword" value="Změnit heslo">
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <h5 class="card-header">Platby</h5>
                    <div class="card-body">
                        <form class="card-text" action="" method="post">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Jméno:</label>
                                <div class="col">
                                    <select autofocus name="admin-showpayments-user" class="form-control">
                                        <?php foreach ($this->data["familyUsers"] as $user): ?>
                                            <?php if ($user["userid"] != Ssn::get("loggedUser")["userid"]): ?>
                                                <option value="<?php echo $user['userid']; ?>"><?php echo $user["username"]; ?></option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <input class="btn btn-lg btn-success btn-block" type="submit" name="admin-showpayments" value="Zobrazit platby">
                        <div class="container">
                            <?php if (isset($this->data["show-payments"])): ?>
                                <table class="table table-striped table-sm">
                                    <thead>
                                        <tr>
                                            <th>Měsíc</th>
                                            <th>Rok</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->data["show-payments"] as $_payment): ?>
                                            <tr>
                                                <td><?php echo $_payment["month"] ?></td>
                                                <td><?php echo $_payment["year"] ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif ?>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>
</body>