<body>
	<div class="section">
		<div class="container">
			<main>
				<div class="columns login">
					<div class="column has-text-centered is-full-mobile is-half-tablet is-one-third-desktop">
						<form action="" id="form-login" class="form-login box" method="post">
							<div class="block">
								<h1 class="is-size-4">Přihlášení</h1>
							</div>
							<div class="block">
								<div class="field">
									<div class="control has-icons-left">
										<input type="text" id="login-username" name="login-username" class="input" placeholder="Jméno" required="required">
										<span class="icon is-small is-left">
											<i class="fas fa-user"></i>
										</span>
									</div>
								</div>
								<div class="field">
									<div class="control has-icons-left">
										<input type="password" id="login-password" name="login-password" class="input" placeholder="Heslo" required="required">
										<span class="icon is-small is-left">
											<i class="fas fa-lock"></i>
										</span>
									</div>
								</div>
							</div>
							<div class="field">
								<div class="control has-text-centered">
									<input type="submit" id="signin" class="button is-medium is-fullwidth is-primary" name="login" value="Přihlásit se">
								</div>
							</div>
						</form>
					</div>
				</div>
			</main>
		</div>
	</div>
	
</body>