<body class="login">
    <form class="form-signin" action="" method="post">
        <input type="hidden" name="login" value="1">
        <h1 class="h3 mb-3 font-weight-normal">Přihlášení</h1>
        <label class="sr-only">Jméno</label>
        <input type="text" name="login-username" class="form-control" placeholder="Jméno" required="required">
        <label class="sr-only">Heslo</label>
        <input type="password" name="login-password" class="form-control" placeholder="Heslo" required="required"></br>
        <input type="submit" class="btn btn-lg btn-success btn-block" value="Přihlásit se">
        <p class="mt-5 mb-3 text-muted">&copy;2020 Platby.tk</p>
    </form>
</body>