<body>
	<div class="section">
		<div class="container">
			<main>
				<div class="columns">
					<div class="column is-full-mobile is-one-third-tablet">
						<div class="block">
							<div class="card">
								<div class="card">
									<header class="card-header">
										<p class="card-header-title">
											Uživatelské informace
										</p>
									</header>
									<div class="card-content">
										<div class="content">
											<p>
												Přihlášen jako <?php echo Ssn::get("loggedUser")["username"] ?><br>
												(skupina <?php echo Ssn::get("loggedUser")["familyid"] ?>)
											</p>
										</div>
									</div>
									<form action="" method="post">
										<footer class="card-footer">
											<input class="button is-dark is-fullwidth is-medium" type="submit" name="logout" value="Odhlásit se">
										</footer>
									</form>
								</div>
							</div>
						</div>
						<div class="block">
							<div class="card">
								<header class="card-header">
									<p class="card-header-title">
										Změna hesla
									</p>
								</header>
								<form action="" method="post">
									<div class="card-content">
										<div class="content">
											<div class="field is-horizontal">
												<div class="field-label is-normal">
													<label for="" class="label">Heslo:</label>
												</div>
												<div class="field-body">
													<div class="field">
														<div class="control is-expanded">
															<input class="input" type="password" name="changepassword-password" required="required">
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card-footer">
										<input class="button is-light is-medium is-fullwidth" type="submit" name="changepassword" value="Změnit heslo">
									</div>
								</form>
							</div>
						</div>
						<?php if (!PaymentModel::isPayment(Ssn::get("loggedUser")["userid"], (int)date("m"), (int)"20".date("y"))): ?>
						<div class="block">
							<div class="card">
								<div class="card-content">
									<div class="content">
										<img src="http://api.paylibo.com/paylibo/generator/czech/image
										?accountNumber=<?php echo $this->data["qrdata"]["accountNumber"] ?>
										&bankCode=<?php echo $this->data["qrdata"]["bankCode"] ?>
										&amount=<?php echo $this->data["qrdata"]["amount"] ?>
										&currency=CZK
										&message=<?php echo "PLATBA SPOTIFY " . (int)date("m") . "/" . (int)date("y") . " | " . Ssn::get("loggedUser")["username"]?>"
										style="min-width: 100%;">
									</div>
								</div>
							</div>
						</div>
						<?php else: ?>
							<div class="notification is-primary">
								<button class="delete"></button>
								<p>Pro tento měsíc již máte zaplaceno.</p>
							</div>
						<?php endif ?>
					</div>
					<div class="column is-full-mobile is-two-thirds-tablet">
						<div class="block">
							<div class="card">
								<div class="card-content">
									<div class="content">
										<table class="table is-fullwidth is-striped is-hoverable">
											<thead>
												<tr>
													<th>Měsíc</th>
													<th>Rok</th>
												</tr>
											</thead>
											<tbody>
												<?php foreach ($this->data["payments"] as $_payment): ?>
												<tr
													<?php if ($_payment["month"] == (int)date("m")& $_payment["year"] == (int)"20".date("y")): ?>
													class="is-selected"
													<?php endif; ?>
													>
													<td><?php echo $_payment["month"] ?></td>
													<td><?php echo $_payment["year"] ?></td>
												</tr>
												<?php endforeach; ?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="column is-full-mobile is-one-third-tablet">
						
					</div>
				</div>
			</main>
		</div>
	</div>
</body>