<body>
	<div class="container">
		<br>
		<div class="row">
			<div class="col-sm-8 mb-3">
				<div class="card">
					<h5 class="card-header">
						Platby
					</h5>
					<div class="card-body">
						<table class="table table-striped table-sm">
							<thead>
								<tr>
									<th>Měsíc</th>
									<th>Rok</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($this->data["payments"] as $_payment): ?>
									<tr>
										<td><?php echo $_payment["month"] ?></td>
										<td><?php echo $_payment["year"] ?></td>
									</tr>
								<?php endforeach ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="row">
					<div class="col mb-3">
						<div class="card">
							<h5 class="card-header">Uživatelské informace</h5>
							<div class="card-body">
								<p>Přihlášen jako <?php echo Ssn::get("loggedUser")["username"] ?> (skupina <?php echo Ssn::get("loggedUser")["familyid"] ?>)</p>
							</div>
							<form action="" method="post">
								<input class="btn btn-danger btn-block" type="submit" name="logout" value="Odhlásit se">
							</form>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col mb-3">
						<div class="card">
							<h5 class="card-header">Změna hesla</h5>
							<form action="" method="post">
								<div class="form-group row">
									<div class="col mx-3 mt-3">
										<input type="password" class="form-control" name="new-password">
									</div>
								</div>
								<input type="submit" class="btn btn-warning btn-block" name="changepassword" value="Změnit heslo">
							</form>
						</div>
					</div>
				</div>
				<?php if (!PaymentModel::isPayment(Ssn::get("loggedUser")["userid"], (int)date("m"), (int)"20".date("y"))): ?>
					<div class="row">
						<div class="col mb-3">
							<div class="card">
								<img src="http://api.paylibo.com/paylibo/generator/czech/image
								?accountNumber=<?php echo $this->data["qrdata"]["accountNumber"] ?>
								&bankCode=<?php echo $this->data["qrdata"]["bankCode"] ?>
								&amount=<?php echo $this->data["qrdata"]["amount"] ?>
								&currency=CZK
								&message=<?php echo "PLATBA SPOTIFY " . (int)date("m") . "/" . (int)date("y") . " | " . Ssn::get("loggedUser")["username"]?>">
							</div>
						</div>
					</div>
				<?php endif ?>
			</div>
		</div>
		<br>
	</div>
</body>